export const _EVENTS = {
  esc_click: 'esc_click',
  switch_to_game_scene: 'switch_to_game_scene',
  shop_menu_open: 'shop_menu_open',
  shop_menu_close: 'shop_menu_close',
  plant_menu_open: 'plant_menu_open',
  plant_menu_close: 'plant_menu_close',
  picked_plant_show: 'picked_plant_show',
  picked_plant_hide: 'picked_plant_hide',
  picked_plant_update: 'picked_plant_update',
  picked_plant_clear: 'picked_plant_clear',
  balance_update_coins: 'balance_update_coins',
  balance_update_tokens: 'balance_update_tokens',
  balance_update_xp: 'balance_update_xp',
  balance_show: 'balance_show',
  balance_hide: 'balance_hide',
  ring_show: 'ring_show',
  ring_hide: 'ring_hide',
  ring_set_menu: 'ring_set_menu',
  ring_set_escape: 'ring_set_escape'
};
