export const PLANT_COORDS = [
  [
    { x: -47, y: -30, texture: "plant" },
    { x: -31, y: -20, texture: "grass" },
    { x: -15, y: -10, texture: "plant" },
    { x: 0, y: 0, texture: "soil" },
    { x: 15, y: 10, texture: "soil" },
    { x: 31, y: 20, texture: "soil" },
    { x: 47, y: 30, texture: "soil" },
  ],
  [
    { x: -47, y: -30, texture: "soil" },
    { x: -31, y: -20, texture: "soil" },
    { x: -15, y: -10, texture: "soil" },
    { x: 0, y: 0, texture: "soil" },
    { x: 15, y: 10, texture: "soil" },
    { x: 31, y: 20, texture: "soil" },
    { x: 47, y: 30, texture: "soil" },
  ],
  [
    { x: -47, y: -30, texture: "soil" },
    { x: -31, y: -20, texture: "soil" },
    { x: -15, y: -10, texture: "soil" },
    { x: 0, y: 0, texture: "plant" },
    { x: 15, y: 10, texture: "soil" },
    { x: 31, y: 20, texture: "soil" },
    { x: 47, y: 30, texture: "soil" },
  ],
  [
    { x: -47, y: -30, texture: "plant" },
    { x: -31, y: -20, texture: "plant" },
    { x: -15, y: -10, texture: "soil" },
    { x: 0, y: 0, texture: "grass" },
    { x: 15, y: 10, texture: "soil" },
    { x: 31, y: 20, texture: "soil" },
    { x: 47, y: 30, texture: "soil" },
  ],
  [
    { x: -47, y: -30, texture: "soil" },
    { x: -31, y: -20, texture: "soil" },
    { x: -15, y: -10, texture: "soil" },
    { x: 0, y: 0, texture: "soil" },
    { x: 15, y: 10, texture: "soil" },
    { x: 31, y: 20, texture: "grass" },
    { x: 47, y: 30, texture: "grass" },
  ],
  [
    { x: -47, y: -30, texture: "soil" },
    { x: -31, y: -20, texture: "soil" },
    { x: -15, y: -10, texture: "soil" },
    { x: 0, y: 0, texture: "plant" },
    { x: 15, y: 10, texture: "grass" },
    { x: 31, y: 20, texture: "soil" },
    { x: 47, y: 30, texture: "soil" },
  ],
  [
    { x: -47, y: -30, texture: "soil" },
    { x: -31, y: -20, texture: "grass" },
    { x: -15, y: -10, texture: "soil" },
    { x: 0, y: 0, texture: "soil" },
    { x: 15, y: 10, texture: "soil" },
    { x: 31, y: 20, texture: "plant" },
    { x: 47, y: 30, texture: "plant" },
  ],
];
